---
- name: Check if the LXC container exists
  command: lxc info {{ container_name_nginx }}
  register: container_check
  ignore_errors: true
  changed_when: false

- name: Create LXC container nginx
  when: container_check.failed
  command: lxc init ubuntu:24.04 {{ container_name_nginx }}
  become: yes

- name: Check if the container is running
  register: container_status
  changed_when: false
  become: yes
  ignore_errors: true
  shell: |
    lxc info {{ container_name_nginx }} | grep -q "Status: RUNNING"

- name: Start LXC container nginx
  command: lxc start {{ container_name_nginx }}
  when: container_status.rc != 0

- name: Wait for the LXC container to be fully running
  shell: |
    lxc info {{ container_name_nginx }} | grep -q "Status: RUNNING"
  register: container_running
  retries: 3  # Number of retries
  delay: 3    # Wait n seconds between retries
  until: container_running.rc == 0
  changed_when: false
  ignore_errors: false

- name: Ensure LXC container nginx starts on boot
  command: lxc-autostart -n {{ container_name_nginx }}

- name: Get LXC container IP address
  register: container_ip
  changed_when: false
  become: yes
  shell: |
    lxc info {{ container_name_nginx }} | grep "inet: .* (global)" | awk '{ print $2 }' | awk -F/ '{ print $1 }';

- name: Add LXC container to Ansible inventory
  add_host:
    name: "{{ container_name_nginx }}"
    ansible_host: "{{ container_ip.stdout }}"
    ansible_user: ubuntu
  delegate_to: localhost

# - name: Gather facts from nginx-container
#   setup:
#     delegate_to: nginx-container