---
- name: Install LXC
  import_tasks: install.yml
  vars:
    nextcloud_directory: /var/www/nextcloud

- name: Setup LXC for "{{ item }}"
  include_tasks: lxc_{{ item }}.yml
  loop:
    - nginx
    - dokuwiki
    - zulip
    - nextcloud
  vars:
    container_name_nginx: nginx-container
    container_name_dokuwiki: dokuwiki-container
    container_name_zulip: zulip-container
    container_name_nextcloud: nextcloud-container
