---

- name: Ensure /opt/bigbluebutton directory exists
  file:
    path: /opt/bigbluebutton
    state: directory
    mode: '0755'
  become: yes

- name: Download BigBlueButton installation script
  get_url:
    url: https://raw.githubusercontent.com/bigbluebutton/bbb-install/v2.7.x-release/bbb-install.sh
    dest: /opt/bigbluebutton/bbb-install.sh
    mode: '0755'
  become: yes

- name: Install language pack for English
  apt:
    name: language-pack-en
    state: present
    update_cache: yes
  become: yes

- name: Update system locale
  command: update-locale LANG=en_US.UTF-8
  become: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Download BigBlueButton repository key
  get_url:
    url: https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc
    dest: /tmp/bigbluebutton.asc
  become: yes

- name: Add BigBlueButton repository key
  apt_key:
    file: /tmp/bigbluebutton.asc
    state: present
    keyring: /etc/apt/trusted.gpg.d/bigbluebutton.gpg
  become: yes

- name: Update APT cache
  apt:
    update_cache: yes
  become: yes

- name: Execute BigBlueButton installation script
  command: /opt/bigbluebutton/bbb-install.sh -v focal-270
  become: yes
  failed_when: result.rc != 0

- name: Display BigBlueButton installation script output
  debug:
    msg: "{{ result.stdout }}\n{{ result.stderr }}"


- name: Install BigBlueButton and dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - bigbluebutton
    - bbb-web
    - bbb-freeswitch
    - bbb-java
  become: yes

- name: Install additional dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nginx
    - redis-server
    - mariadb-server
  become: yes

- name: Ensure services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nginx
    - redis-server
    - mariadb
    - bbb-web
    - bbb-freeswitch
  become: yes
