---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - unzip
    - docker.io

- name: Add entry to /etc/hosts
  lineinfile:
    path: /etc/hosts
    state: present
    line: "127.0.0.1 healthnexus.online"