# Vagrantfile to set up a Linux VM (Ubuntu) for use with Ansible
Vagrant.configure("2") do |config|
    # Use Ubuntu 22.04 LTS as the base box
    config.vm.box = "ubuntu/jammy64"
    
    # Configure VM details
    config.vm.hostname = "HealthNexus"
    config.vm.network "private_network", type: "dhcp"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "AnsibleEnvironment"
      vb.memory = "4096"
      vb.cpus = 4
    end
  
    # Forward ports if needed
    # Flask app
    config.vm.network "forwarded_port", guest: 5000, host: 5000

    # Provisioning with shell script to install Ansible
    config.vm.provision "shell", inline: <<-SHELL
      # Update and install prerequisites
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get install -y software-properties-common 

      # Add Ansible PPA and install Ansible
      sudo apt-add-repository --yes --update ppa:ansible/ansible
      sudo apt-get update
      sudo apt-get install -y ansible

      # For flask webserver
      sudo apt-get install -y python-is-python3 python3-pip python3-flask python3.10-venv

      # Convenience tools
      sudo apt-get install -y tree
    SHELL
  
    config.vm.provision "shell", inline: <<-SHELL
      sudo mkdir -p /opt/HealthNexus
      sudo chown vagrant:vagrant /opt/HealthNexus
    SHELL

    # Synced folder to access the host files
    config.vm.synced_folder "../", "/opt/HealthNexus", type: "rsync"

    # SSH configurations (Optional)
    config.ssh.insert_key = false
    config.ssh.forward_agent = true

    # # Provisioning with Ansible from host
    # config.vm.provision "ansible" do |ansible|
    #     ansible.playbook = "../ansible/playbook.yml"
    #     ansible.inventory_path = "../ansible/inventory"
    # end

    # Provisioning with Ansible from guest
    # config.vm.provision "ansible_local" do |ansible|
    #     ansible.playbook = "/vagrant/ansible/playbook.yml"
    #     ansible.inventory_path = "/vagrant/ansible/inventory"
    # end

    # Provisioning: Copy and execute the script
    config.vm.provision "shell" do |s|
      # Copy the script from the host to the VM
      s.inline = <<-SHELL
        chmod u+x /opt/HealthNexus/src/server/install.sh
        /opt/HealthNexus/src/server/install.sh
      SHELL
    end
  end
  