---
- name: Download Etherpad
  become: yes
  get_url:
    url: "https://github.com/ether/etherpad-lite/archive/refs/tags/{{ etherpad_version }}.tar.gz"
    dest: /tmp/etherpad-lite-{{ etherpad_version }}.tar.gz

- name: Create /opt/etherpad directory
  file:
    path: /opt/etherpad
    state: directory
    owner: etherpad
    group: etherpad
    mode: '0755'

- name: Extract Etherpad
  become: yes
  unarchive:
    src: /tmp/etherpad-lite-{{ etherpad_version }}.tar.gz
    dest: "{{ etherpad_install_dir }}"
    remote_src: yes

- name: Set ownership of Etherpad directory
  become: yes
  file:
    path: "{{ etherpad_install_dir }}"
    owner: "{{ etherpad_user }}"
    group: "{{ etherpad_group }}"
    state: directory
    recurse: yes

- name: Configure Etherpad
  template:
    src: etherpad_config.json.j2
    dest: "{{ etherpad_config_file }}"
  become: yes
