---
# - name: Update package list
#   apt:
#     update_cache: yes
#   become: yes

# - name: Fix broken packages
#   apt:
#     force: yes
#   become: yes

# - name: Clean up unnecessary packages and cache
#   apt:
#     autoremove: yes
#     autoclean: yes
#   become: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: present
  become: yes

- name: Install npm
  apt:
    name: npm
    state: present
  become: yes
  ignore_errors: yes

- name: Install Redis
  apt:
    name: redis-server
    state: present
  become: yes

- name: Ensure Etherpad group exists
  group:
    name: etherpad
    state: present
  become: yes

- name: Create Etherpad user
  user:
    name: "{{ etherpad_user }}"
    group: "{{ etherpad_group }}"
    create_home: no
    shell: /bin/false
  become: yes
