---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes

# - name: Create healthnexus dir
#   file:
#     path: /etc/nginx/sites-available/healthnexus
#     state: directory
#     mode: '0644'
#   become: yes

- name: Copy Nginx configuration
  copy:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/healthnexus
    mode: '0644'
  become: yes

- name: Enable HealthNexus site
  file:
    src: /etc/nginx/sites-available/healthnexus
    dest: /etc/nginx/sites-enabled/healthnexus
    state: link
  become: yes

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Test Nginx configuration
  command: nginx -t
  become: yes

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
  become: yes
