- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Pull the Zulip Docker image
  docker_image:
    name: zulip/docker-zulip:latest
    source: pull

- name: Run Zulip Docker container
  docker_container:
    name: zulip
    image: zulip/docker-zulip
    state: started
    restart_policy: always
    published_ports:
      - "1180:1180"      # Adjust ports as needed
      - "11443:11443"    # Adjust ports as needed
    volumes:
      - /zulip:/zulip   # Adjust volumes as needed
    env:
      ZULIP_ADMIN_EMAIL: admin@example.com  # Replace with actual admin email
      ZULIP_ADMIN_PASSWORD: yourpassword     # Replace with actual admin password
