---
- name: Setup HealthNexus
  hosts: healthnexus_server
  become: yes
  roles:
    - setup
    - nginx
    - haproxy
    - zulip
    - nextcloud
    - bigbluebutton
    - dokuwiki
    - keycloak_ldap

- name: Backup all services
  hosts: all
  become: yes
  roles:
    - backup
