---
- name: Setup HealthNexus
  hosts: healthnexus_server local
  become: yes
  roles:
    - setup
    - nginx
    - haproxy
    - zulip
    - nextcloud
    - bigbluebutton
    - dokuwiki
    - etherpad
    - mumble
    - cryptpad
    # - keycloak_ldap
    # - ldap_sso

# - name: Backup all services
#   hosts: all
#   become: yes
#   roles:
#     - backup
                                                    

