---
- name: Setup HealthNexus
  hosts: healthnexus_server local
  become: yes
  roles:
    # - setup
    - lxc
    # - nginx
    # - haproxy
    # - zulip
    # - nextcloud
    # - bigbluebutton
    # - dokuwiki
    # - etherpad
    # - mumble
    # - cryptpad
    # - keycloak_ldap
    # - ldap_sso

- name: Setup nginx
  hosts: lxc_containers
  roles:
    - nginx



# - name: Backup all services
#   hosts: all
#   become: yes
#   roles:
#     - backup
                                                    

